apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "postgres.fullname" . }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "python-api.fullname" . }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: postgres
