apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "python-api.fullname" . }}
  annotations:
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.nginx.domain }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Values.service.name }}
            port:
              number: 8000