trigger:
- main

name: infra-pipeline

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformCLI@2
  inputs:
    command: 'init'
    workingDirectory: 'infra'

- task: TerraformCLI@2
  inputs:
    command: 'plan'
    workingDirectory: 'infra'
    environmentServiceNameAzureRM: 'AZURE_SERVICE_CONNECTION_NAME'
    backendServiceArm: 'AZURE_SERVICE_CONNECTION_NAME'
    backendAzureRmResourceGroupName: 'TERRAFORM_STATE_RESOURCE_GROUP'
    backendAzureRmStorageAccountName: 'TERRAFORM_STATE_STORAGE_ACCOUNT'
    backendAzureRmContainerName: 'TERRAFORM_STATE_CONTAINER'
    backendAzureRmKey: 'terraform.tfstate'

- task: ManualValidation@0
  inputs:
    notifyUsers: |
      emailaddress@email.com
    instructions: 'Review and approve the Terraform plan.'
    onTimeout: 'reject'
    timeoutInMinutes: 10080

- task: TerraformCLI@2
  inputs:
    command: 'apply'
    workingDirectory: 'infra'
    environmentServiceNameAzureRM: 'AZURE_SERVICE_CONNECTION_NAME'
    backendServiceArm: 'AZURE_SERVICE_CONNECTION_NAME'
    backendAzureRmResourceGroupName: 'TERRAFORM_STATE_RESOURCE_GROUP'
    backendAzureRmStorageAccountName: 'TERRAFORM_STATE_STORAGE_ACCOUNT'
    backendAzureRmContainerName: 'TERRAFORM_STATE_CONTAINER'
    backendAzureRmKey: 'terraform.tfstate'