trigger:
- main

name: infra-pipeline

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformCLI@2
  inputs:
    command: 'init'
    workingDirectory: '(System.DefaultWorkingDirectory)/terraform'
$
- task: TerraformCLI@2
  inputs:
    command: 'plan'
    workingDirectory: '(System.DefaultWorkingDirectory)/terraform'
    environmentServiceNameAzureRM: 'azure-service-connection'
    backendServiceArm: 'azure-service-connection'
    backendAzureRmResourceGroupName: 'techassessrg'
    backendAzureRmStorageAccountName: 'tfsa'
    backendAzureRmContainerName: 'statefilecontainer'
    backendAzureRmKey: 'terraform.tfstate'

- task: ManualValidation@0
  inputs:
    notifyUsers: |
      ravigeni.20@gmail.com
    instructions: 'Review and approve the Terraform plan.'
    onTimeout: 'reject'
    timeoutInMinutes: 10080

- task: TerraformCLI@2
  inputs:
    command: 'apply'
    workingDirectory: '(System.DefaultWorkingDirectory)/terraform'
    environmentServiceNameAzureRM: 'azure-service-connection'
    backendServiceArm: 'azure-service-connection'
    backendAzureRmResourceGroupName: 'techassessrg'
    backendAzureRmStorageAccountName: 'tfsa'
    backendAzureRmContainerName: 'statefilecontainer'
    backendAzureRmKey: 'terraform.tfstate'